const momentApi = '2022-09-20 17:25:22';

const globalState = {
  user: { email: 'karinsantosmelo@gmail.com' },
  wallet: {
    currencies: [
      'USD',
      'CAD',
      'GBP',
      'ARS',
      'BTC',
      'LTC',
      'EUR',
      'JPY',
      'CHF',
      'AUD',
      'CNY',
      'ILS',
      'ETH',
      'XRP',
      'DOGE',
    ],
    expenses: [
      {
        description: 'viagem',
        value: '1200',
        currency: 'EUR',
        method: 'Cartão de crédito',
        tag: 'Lazer',
        id: 0,
        exchangeRates: {
          USD: {
            code: 'BRL',
            codein: 'BRL',
            name: 'Dólar Americano/Real Brasileiro',
            high: '5.1435',
            low: '5.143',
            varBid: '0.0013',
            pctChange: '0.03',
            bid: '5.1425',
            ask: '5.1435',
            timestamp: '1663709311',
            create_date: momentApi,
          },
          USDT: {
            code: 'USD',
            codein: 'BRLT',
            name: 'Dólar Americano/Real Brasileiro Turismo',
            high: '5.245',
            low: '5.165',
            varBid: '-0.005',
            pctChange: '-0.1',
            bid: '5.03',
            ask: '5.34',
            timestamp: '1663702260',
            create_date: momentApi,
          },
          CAD: {
            code: 'CAD',
            codein: 'BRL',
            name: 'Dólar Canadense/Real Brasileiro',
            high: '3.8489',
            low: '3.8472',
            varBid: '0.0004',
            pctChange: '0.01',
            bid: '3.848',
            ask: '3.8491',
            timestamp: '1663709312',
            create_date: momentApi,
          },
          GBP: {
            code: 'GBP',
            codein: 'BRL',
            name: 'Libra Esterlina/Real Brasileiro',
            high: '5.8538',
            low: '5.8466',
            varBid: '-0.0012',
            pctChange: '-0.02',
            bid: '5.8517',
            ask: '5.8543',
            timestamp: '1663709312',
            create_date: momentApi,
          },
          ARS: {
            code: 'ARS',
            codein: 'BRL',
            name: 'Peso Argentino/Real Brasileiro',
            high: '0.0356',
            low: '0.0355',
            varBid: '0',
            pctChange: '0',
            bid: '0.0356',
            ask: '0.0356',
            timestamp: '1663709312',
            create_date: momentApi,
          },
          BTC: {
            code: 'BTC',
            codein: 'BRL',
            name: 'Bitcoin/Real Brasileiro',
            high: '102.568',
            low: '97.252',
            varBid: '-3395',
            pctChange: '-3.34',
            bid: '98.218',
            ask: '98.45',
            timestamp: '1663709198',
            create_date: momentApi,
          },
          LTC: {
            code: 'LTC',
            codein: 'BRL',
            name: 'Litecoin/Real Brasileiro',
            high: '279.07',
            low: '266.79',
            varBid: '-2.2',
            pctChange: '-0.81',
            bid: '270.14',
            ask: '270.97',
            timestamp: '1663708765',
            create_date: momentApi,
          },
          EUR: {
            code: 'EUR',
            codein: 'BRL',
            name: 'Euro/Real Brasileiro',
            high: '5.1317',
            low: '5.1276',
            varBid: '-0.0007',
            pctChange: '-0.01',
            bid: '5.1266',
            ask: '5.1296',
            timestamp: '1663709312',
            create_date: momentApi,
          },
          JPY: {
            code: 'JPY',
            codein: 'BRL',
            name: 'Iene Japonês/Real Brasileiro',
            high: '0.0358',
            low: '0.03577',
            varBid: '0',
            pctChange: '0',
            bid: '0.03579',
            ask: '0.03581',
            timestamp: '1663709316',
            create_date: momentApi,
          },
          CHF: {
            code: 'CHF',
            codein: 'BRL',
            name: 'Franco Suíço/Real Brasileiro',
            high: '5.3369',
            low: '5.3303',
            varBid: '0.0004',
            pctChange: '0.01',
            bid: '5.3345',
            ask: '5.3378',
            timestamp: '1663709312',
            create_date: momentApi,
          },
          AUD: {
            code: 'AUD',
            codein: 'BRL',
            name: 'Dólar Australiano/Real Brasileiro',
            high: '3.4427',
            low: '3.4397',
            varBid: '0.0017',
            pctChange: '0.05',
            bid: '3.4419',
            ask: '3.4431',
            timestamp: '1663709317',
            create_date: momentApi,
          },
          CNY: {
            code: 'CNY',
            codein: 'BRL',
            name: 'Yuan Chinês/Real Brasileiro',
            high: '0.7445',
            low: '0.7327',
            varBid: '-0.0054',
            pctChange: '-0.74',
            bid: '0.7327',
            ask: '0.7329',
            timestamp: '1663708264',
            create_date: momentApi,
          },
          ILS: {
            code: 'ILS',
            codein: 'BRL',
            name: 'Novo Shekel Israelense/Real Brasileiro',
            high: '1.5153',
            low: '1.488',
            varBid: '-0.0116',
            pctChange: '-0.77',
            bid: '1.4912',
            ask: '1.4915',
            timestamp: '1663708206',
            create_date: momentApi,
          },
          ETH: {
            code: 'ETH',
            codein: 'BRL',
            name: 'Ethereum/Real Brasileiro',
            high: '7.25683',
            low: '6.91215',
            varBid: '-125.32',
            pctChange: '-1.77',
            bid: '6.94832',
            ask: '6.94832',
            timestamp: '1663708766',
            create_date: momentApi,
          },
          XRP: {
            code: 'XRP',
            codein: 'BRL',
            name: 'XRP/Real Brasileiro',
            high: '2.19',
            low: '1.94',
            varBid: '0.13',
            pctChange: '6.59',
            bid: '2.12',
            ask: '2.12',
            timestamp: '1663709202',
            create_date: momentApi,
          },
          DOGE: {
            code: 'DOGE',
            codein: 'BRL',
            name: 'Dogecoin/Real Brasileiro',
            high: '0.31092',
            low: '0.300219',
            varBid: '-0.00114301',
            pctChange: '-0.38',
            bid: '0.301864',
            ask: '0.301864',
            timestamp: '1663709302',
            create_date: momentApi,
          },
        },
      },
    ],
    editor: false,
    idToEdit: 0,
  },
};

export default globalState;
